name: update lockfile
on:
  # Manual trigger only - go to Actions tab and click "Run workflow"
  workflow_dispatch:
  # Scheduled update (each day) - disabled by default
  # schedule: [{ cron: "30 01 * * *" }]

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required to count the commits
      - uses: andstor/file-existence-action@v3
        id: check_lockfile
        with:
          files: "lazy-lock.json"
      - uses: rhysd/action-setup-vim@v1
        if: ${{ steps.check_lockfile.outputs.files_exists == 'true' }}
        with:
          neovim: true
      - name: Run lockfile-autoupdate
        if: ${{ steps.check_lockfile.outputs.files_exists == 'true' }}
        timeout-minutes: 5
        run: |
          nvim --headless "+Lazy! update" +qa
          cp -pv "${HOME}/.config/nvim/lazy-lock.json" .
      - uses: stefanzweifel/git-auto-commit-action@v6
        if: ${{ steps.check_lockfile.outputs.files_exists == 'true' }}
        with:
          commit_message: "chore(lockfile): auto update lazy-lock.json"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          file_pattern: "lazy-lock.json"
